# ==============================================================================
# USER CONFIGURATION: autostart.conf
# ==============================================================================
# Add your custom settings for autostart here.
# These will override or add to the defaults found in ~/.config/hypr/source/autostart.conf
# ==============================================================================

exec-once = sleep 5 && hyprshade on saturation
exec-once = input-remapper-control --command autoload
exec-once = flatpak run com.github.wwmm.easyeffects --gapplication-service
exec = hyprshade on saturation
