# ==============================================================================
# USER CONFIGURATION: keybinds.conf
# ==============================================================================
# Add your custom settings for keybinds here.
# These will override or add to the defaults found in ~/.config/hypr/source/keybinds.conf
# This file can also be edited with dusky keybinds manager from the rofi menu or from dusky control center
# ==============================================================================

$browser     = zen-browser
$textEditor  = nvim

# -- TERMINAL-CLIPBOARD-START --
unbind = $mainMod, V
bindd = $mainMod, V, Clipboard History, exec, $scripts/clipboard/close_terminal_clipboard.sh uwsm-app -- kitty --class terminal_clipboard.sh -e "$scripts/clipboard/terminal_clipboard.sh"
# -- TERMINAL-CLIPBOARD-END --


# [2026-02-19 13:17] SRC
unbind = $mainMod, apostrophe


# [2026-02-19 13:21] CUST
bindd = $mainMod, numbersign, Cycle Wallpaper, exec, uwsm-app -- $scripts/theme_matugen/theme_ctl.sh random

# [2026-02-20 11:18] CUST
unbind = $mainMod, W
bindd = $mainMod, W, Launch Browser, exec, uwsm-app -- $browser

# [2026-02-20 11:32] SRC
unbind = CTRL SHIFT, escape
bindd = CTRL SHIFT, escape, System Monitor, exec, uwsm-app -- $terminal --class btop -e btop

# [2026-02-20 12:05] UNBIND
unbind = ALT SHIFT, 5

# --- [2026-02-20] REBIND FOCUS MOVEMENT ---
# Unbinding old HJKL focus
unbind = $mainMod, left
unbind = $mainMod, right
unbind = $mainMod, up
unbind = $mainMod, down
# Binding new Arrow focus
bindd = $mainMod, left, Focus Left, movefocus, l
bindd = $mainMod, right, Focus Right, movefocus, r
bindd = $mainMod, up, Focus Up, movefocus, u
bindd = $mainMod, down, Focus Down, movefocus, d

# --- [2026-02-20] REBIND WINDOW MOVEMENT ---
# Unbinding old Shift+HJKL movement
unbind = $mainMod SHIFT, h
unbind = $mainMod SHIFT, l
unbind = $mainMod SHIFT, k
unbind = $mainMod SHIFT, j
# Binding new Shift+HJKL movement
bindd = $mainMod SHIFT, left, Move Left, movewindow, l
bindd = $mainMod SHIFT, right, Move Right, movewindow, r
bindd = $mainMod SHIFT, up, Move Up, movewindow, u
bindd = $mainMod SHIFT, down, Move Down, movewindow, d

# --- [2026-02-20] REBIND WINDOW RESIZING ---
# Unbinding old Arrow resizing
unbind = $mainMod, l
unbind = $mainMod, j
unbind = $mainMod, i
unbind = $mainMod, k
# Binding new IJKL resizing
bindd = $mainMod, l, Resize Width +, resizeactive, 30 0
bindd = $mainMod, j, Resize Width -, resizeactive, -30 0
bindd = $mainMod, i, Resize Height -, resizeactive, 0 -30
bindd = $mainMod, k, Resize Height +, resizeactive, 0 30





# [2026-03-01 13:40] CUST
unbind = $mainMod, Y
bindd = $mainMod, Y, Toggle Split, layoutmsg, togglesplit

bindled = $mainMod CTRL, up, Scale Up, exec, uwsm-app -- $scripts/hypr/adjust_scale.py +
bindled = $mainMod CTRL, down, Scale Down, exec, uwsm-app -- $scripts/hypr/adjust_scale.py -

unbind = $mainMod, F
unbind = $mainMod SHIFT, F
bind = $mainMod, F, layoutmsg, movetoroot
bind = $mainMod, X, layoutmsg, swapsplit

# [2026-03-03 16:43] CUST
unbind = $mainMod, R
bindd = $mainMod, R, Open Text Editor, exec, uwsm-app -- kitty --directory ~/Documents/Text/ $textEditor

# [2026-03-05 20:04] SRC
unbind = SUPER, equal

# [2026-03-05 20:05] CUST
binded = SUPER, KP_Add, Zoom In, exec, sh -c "hyprctl keyword cursor:zoom_factor \"$(hyprctl getoption cursor:zoom_factor | awk 'NR==1 {print $2 * 1.25}')\""

# [2026-03-05 20:06] SRC
unbind = SUPER, minus
binded = SUPER, KP_Subtract, Zoom Out, exec, sh -c "hyprctl keyword cursor:zoom_factor \"$(hyprctl getoption cursor:zoom_factor | awk 'NR==1 {val = $2 / 1.25; if (val < 1.0) val = 1.0; print val}')\""

# [2026-03-05 20:17] SRC
unbind = $mainMod, SPACE
bindd = $mainMod, SPACE, System Menu, exec, uwsm-app -- $scripts/rofi/system_menu.sh




# [2026-03-07 14:55] CUST
bindd = , code:91, Mute Mic, exec, pactl set-source-mute @DEFAULT_SOURCE@ toggle
